language: python

cache: pip

branches:
  only:
    - master
    - unit-tests

# ===== Linux ======
dist: xenial

python:
  - 3.6
  - 3.7
  - 3.8

matrix:
  include:
    #  ====== WINDOWS =========
    - name: "Python 3.6.8 on Windows"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install make
        - choco install python --version 3.6.8
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - PYTHONCALL=python

    - name: "Python 3.7.6 on Windows"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install make
        - choco install python --version 3.7.6
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - PYTHONCALL=python

    - name: "Python 3.8.1 on Windows"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install make
        - choco install python --version 3.8.1
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - PYTHONCALL=python

# install dependencies
install:
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install poetry
  - make devsetup

# run tests
script:
  - make autotest
